version: "3.4"
services:
  app:
    image: clemenko/flask_demo
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
    ports:
      - 5000:5000
    networks:
      db:
      kv:

  mongo:
    image: mongo
    networks:
      db:

  redis:
    image: redis:alpine
    networks:
      kv:

networks:
  kv:
  db:
